### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by marius92mc** [marius92mc/Software_Project_Management#5]
Marius&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  - Partea II - subpunctele 4, 5
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Partea  I - detalii privind solutia propusa  

@StefanLache  &nbsp; - Partea II - subpunctele 1, 2 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;  - Partea  I - obiective, motivatie, rezumat, impactul proiectului 

@dany123 &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;  - Partea II -  

@hasnarobert &nbsp; - Partea II - @hasnarobert

**Comment by hasnarobert** [comment]
Am mutat informatie pe pagina de wiki: https://github.com/marius92mc/Software_Project_Management/wiki/Task-List
